name: MSVC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: get latest revision
      id: rev
      run: git rev-list --tags --max-count=1 >> $GITREV
    - name: get latest tag
      id: tagname
      run: git describe --tags $GITREV >> $GIT_TAG_NAME
    - name: get latest tag timestamp
      id: timestamp
      run: git log -1 --format=%at $GITREV >> $GIT_TAG_TIMESTAMP
    - name: Integrate vcpkg
      run: vcpkg integrate install
    - name: Build vcpkg libraries
      run: vcpkg install freetype glfw3 capstone[arm,arm64,x86] --triplet x64-windows-static
    - name: Profiler GUI Release
      run: msbuild .\profiler\build\win32\Tracy.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Update utility Release
      run: msbuild .\update\build\win32\update.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Capture utility Release
      run: msbuild .\capture\build\win32\capture.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Csvexport utility Release
      run: msbuild .\csvexport\build\win32\csvexport.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Import-chrome utility Release
      run: msbuild .\import-chrome\build\win32\import-chrome.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Library Release
      run: msbuild .\library\win32\TracyProfiler.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Package binaries
      run: |
        pwsh -command "${{github.workspace}}\Firestorm-3p\prepare-3p.ps1 -tracy_folder_root ${{github.workspace}}"
    - name: Make tarball
      uses: beqjanus/tar-action@master
      id: tarfile
      env:
        TARBALL_NAME: Tracy-${GIT_TAG_NAME}-windows64-${GIT_TAG_TIMESTAMP}.tar
      with:
        command: c
        cwd: ./3p
        files: |
          bin
          include
          lib
        outPath: $TARBALL_NAME
    - name: bzip it
      run: |
        bzip2 $TARBALL_NAME
    - uses: actions/upload-artifact@v2
      with:
        path: $TARBALL_NAME.bz2
